### ISSUE TITLE
Create a SchemaStore to hold all of the locations where schemas exist  

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#1]
A service/class needs to exist that can be told where a schema dir exists.  This will be used by all pbj-schema-store repositories (in the require-dev section of composer) to register its own directory.

The schema store should be able to:
- addDir -adds a directory where schemas exist.
- getDirs - returns an array of directories where schemas should exist
- getSchemaById - returns a schema by its id.  This is NOT the Gdbots\Pbj\Schema object.  It contains more info (from the yaml) about how to build this schema into multiple languages.  the pbj-php is specifically for php (assuming it's already been compiled).

When a directory is added, do not scan the directory for schemas.  That will only be done when/if the compiler is run.   When a compile request is submitted it will scan all directories for schemas.  The directory must be in this exact structure "vendor/package/category/message/SCHEMAVERSION.yml".  The store MUST throw an exception if the same schema is attempted to be added multiple times.

Schema store is the only class that should be aware of all schemas and their locations on disk.

**Comment by gdbrown** [comment]
- needs to be static methods and don't make "addSchema" public.
- isset is faster that array_key_exists
- add dirs can store string in key to prevent dups, rather than check in_array
- getSchemaById should throw an exception if not found
- start a unit test for this class as well.

we can use the schemaid regex but let's remove the pbj-php lib use.  I want this repo to be as light as possible on the requirements.

**Comment by gdbrown** [comment]
schema store still needs some work.  i only stubbed the functionality.  we also need to make sure the store itself doesn't have too many responsibilities.  what's the use of getting a schema by curie and with major rev.  in what scenario would i need to get schemas by anything other than the full qualified id?

**Comment by excelwebzone** [comment]
In the case on `any_of` the schema id defined using the curie (ex: `gdbots:pbj:mixin:request`). And in the case of `mixins` we use the curie and major (ex: `gdbots:pbj:mixin:request:v1`).

**Comment by gdbrown** [comment]
that makes sense.  can you simplify those methods.  you can store an assoc array by id, curie and curie with major rev.  and the methods should not have schema id.  getSchemaById(SchemaId), getSchemaByCurie(MessageCurie, $majorVersion = null).

addSchema should be internal only or at least not allow for the ignore duplicate option.

anything adding/referencing schemas in the store should use the SchemaId type hint.

**Comment by excelwebzone** [comment]
I don't think we should combine those functions into one, it will just make it more complex as we will need to split each schema id string into it's element (curie, version, etc.. ) every time we want to check if exists.

**Comment by gdbrown** [comment]
if you eliminate the lookup logic and just have buckets for each lookup type the function becomes tiny.

**Comment by excelwebzone** [comment]
Array structure is: `[curie][major][version]`
