### ISSUE TITLE
Test case and example of map, set and list in json schema

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#13]
pbj has map, set, list for multi-valued fields.  We need a test case to ensure those are properly compiled and using unique items and pattern properties...
http://spacetelescope.github.io/understanding-json-schema/reference/array.html#uniqueness

**Comment by gdbrown** [comment]
@excelwebzone  do we have a validation that ensures someone can't use a "set" unless the type allows for it?

**Comment by excelwebzone** [comment]
Right now schema is not handling set rule - if you have an example for it..

**Comment by excelwebzone** [comment]
The following exception will be thrown `Field [tags] with type [message] cannot be used in a set.` for:

``` xml
      <field name="tags" type="message" rule="set"/>
```

``` php
    /**
     * @throws \InvalidArgumentException
     */
    private function applyFieldRule()
    {
        $this->rule = $this->rule ?: FieldRule::A_SINGLE_VALUE();
        if ($this->isASet() && !$this->type->allowedInSet()) {
            throw new \InvalidArgumentException(
                sprintf(
                    'Field [%s] with type [%s] cannot be used in a set.',
                    $this->name,
                    $this->type->getTypeValue()
                )
            );
        }
    }
```
