### ISSUE TITLE
BUG :: json schema for "search-events-response" produces null output

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#27]
The following schema "pbj:gdbots:pbjx:mixin:search-events-response:1-0-0" in `gdbots/schemas` produces a null json schema output.

**Comment by excelwebzone** [comment]
<img width="705" alt="screen shot 2016-05-31 at 6 35 30 am" src="https://cloud.githubusercontent.com/assets/4467438/15676125/f2c02d12-26f9-11e6-9f3c-856ff42e8ea6.png">
