### ISSUE TITLE
Create a realistic example of "acme" vendor with "blog" service.

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#3]
We need a more real world example of messages that will cover all field types and rules.  It will make it easier to follow how the schemas should be used/designed.

**Comment by gdbrown** [comment]
that current compiler is throwing an exception on the "article" entity when I add a "tags" field:
`<field name="tags" type="string" rule="a-set" />`, message `Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Field [tags] with type [string] cannot be used in a set.' in /Users/greg/www/gdbots/pbjc-php/src/Field.php:182`

**Comment by excelwebzone** [comment]
> Note: `string` type doesn't support ASet (allowedInSet() is true) - this was taken from [gdbots/pbj-php](https://github.com/gdbots/pbj-php/blob/master/src/Field.php) repo (line 174)

**Comment by gdbrown** [comment]
string type definitely supports it.  line 174 in what file?

we're using strings in sets in many places currently.

**Comment by excelwebzone** [comment]
Ya, I fixed that. see my last commit.
