### ISSUE TITLE
BUG :: Unable to change default on overridden field

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#31]
Error: The schema "pbj:eme:solicits:edge:submissions:1-0-0" field "default" is invalid. See inherited mixin fields.

```
<?xml version="1.0" encoding="UTF-8" ?>
<pbj-schema xmlns="http://gdbots.io/pbj/xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://gdbots.io/pbj/xsd http://gdbots.io/pbj/xsd/schema.xsd">

  <!--
    This edge helps answer these questions:
    + What submissions have we received for solicit ABC?
    + What submissions has user XYZ sent to us?
  -->
  <schema id="pbj:eme:solicits:edge:submissions:1-0-0">
    <fields>
      <field name="multiplicity" type="string-enum">
        <default>multi</default> <!-- only works with parent default -->
        <!--
        <default>one2many</default><!-- should work -->
        -->
        <enum id="gdbots:ncr:edge-multiplicity"/>
      </field>
    </fields>

    <mixins>
      <curie-major>gdbots:ncr:mixin:edge:v1</curie-major>
    </mixins>

  </schema>
</pbj-schema>

```

**Comment by gdbrown** [comment]
ignoring the inherited field now allows for use of an invalid default.  e.g.

```
<default>what</default>
```

**Comment by gdbrown** [comment]
do you have a unit test for the enum builder?

**Comment by excelwebzone** [comment]
Yes, you can check `EnumDescriptorTest.php` and `EnumParserTest.php`

**Comment by excelwebzone** [comment]
If what is invalid (using PHP) it will convert it to unknown value which should be added to enum class

**Comment by excelwebzone** [comment]
see: https://github.com/gdbots/pbjc-php/blob/master/src/Generator/PhpGenerator.php

``` php
            if (null === $field->getLanguage('php')->get('default', null)) {
                $default = $field->getDefault();
                if (is_array($default)) {
                    $default = count($default) ? current($default) : null;
                }

                $enumKey = 'unknown';
                if ($enum->hasValue($default)) {
                    $enumKey = $enum->getKeyByValue($default);
                }

                $field->getLanguage('php')->set('default', sprintf('%s::%s()', substr($className, strrpos($className, '\\') + 1), strtoupper($enumKey)));

                if (strlen($default) === 0) {
                    $field->getLanguage('php')->set('hide_default', true);
                }
            }
```

**Comment by gdbrown** [comment]
if someone provides an invalid default for an enum field I think it should throw an exception.  the silent conversion of default to unknown is not ideal.  i only noticed it after reviewing the changeset.

i think i'll add a unit test in the schema repos to instantiate all messages from the manifest to ensure the compilation works for all messages.

**Comment by gdbrown** [comment]
this error is backwards... "    The schema "pbj:eme:solicits:edge:submissions:1-0-0" field "one2many11" enum value "multiplicity" doesn't exists. Check enum "gdbots:ncr:edge-multiplicity" for all existing values.  
"

should be:

"    The schema "pbj:eme:solicits:edge:submissions:1-0-0" field "multiplicity" enum value "one2many11" doesn't exist. Check enum "gdbots:ncr:edge-multiplicity" for all existing values.  
"
